// <auto-generated />
using System;
using Consumer.Messaging.Worker.Infrastructure.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Consumer.Messaging.Worker.Migrations
{
    [DbContext(typeof(ChatDbContext))]
    partial class ChatDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Consumer.Messaging.Worker.Domain.Entities.Conversacion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreadoAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creado_at")
                        .HasDefaultValueSql("now()");

                    b.Property<bool>("EsGrupal")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("es_grupal");

                    b.Property<string>("Nombre")
                        .HasColumnType("text")
                        .HasColumnName("nombre");

                    b.HasKey("Id");

                    b.ToTable("conversaciones", (string)null);
                });

            modelBuilder.Entity("Consumer.Messaging.Worker.Domain.Entities.Mensaje", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Contenido")
                        .HasColumnType("text")
                        .HasColumnName("contenido");

                    b.Property<Guid>("ConversacionId")
                        .HasColumnType("uuid")
                        .HasColumnName("conversacion_id");

                    b.Property<DateTime>("CreadoAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creado_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("EmisorId")
                        .HasColumnType("uuid")
                        .HasColumnName("emisor_id");

                    b.Property<int>("TipoMensajeId")
                        .HasColumnType("integer")
                        .HasColumnName("tipo_mensaje_id");

                    b.HasKey("Id");

                    b.HasIndex("ConversacionId");

                    b.HasIndex("TipoMensajeId");

                    b.ToTable("mensajes", (string)null);
                });

            modelBuilder.Entity("Consumer.Messaging.Worker.Domain.Entities.ParticipanteConversacion", b =>
                {
                    b.Property<Guid>("ConversacionId")
                        .HasColumnType("uuid")
                        .HasColumnName("conversacion_id");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.Property<DateTime>("CreadoAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("unido_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTime?>("UltimoLeidoAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ultimo_leido_at");

                    b.HasKey("ConversacionId", "UsuarioId");

                    b.ToTable("participantes_conversacion", (string)null);
                });

            modelBuilder.Entity("Consumer.Messaging.Worker.Domain.Entities.TipoMensaje", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("codigo");

                    b.Property<string>("Descripcion")
                        .HasColumnType("text")
                        .HasColumnName("descripcion");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.ToTable("tipos_mensaje", (string)null);
                });

            modelBuilder.Entity("Consumer.Messaging.Worker.Domain.Entities.Mensaje", b =>
                {
                    b.HasOne("Consumer.Messaging.Worker.Domain.Entities.Conversacion", "Conversacion")
                        .WithMany("Mensajes")
                        .HasForeignKey("ConversacionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Consumer.Messaging.Worker.Domain.Entities.TipoMensaje", "TipoMensaje")
                        .WithMany("Mensajes")
                        .HasForeignKey("TipoMensajeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Conversacion");

                    b.Navigation("TipoMensaje");
                });

            modelBuilder.Entity("Consumer.Messaging.Worker.Domain.Entities.ParticipanteConversacion", b =>
                {
                    b.HasOne("Consumer.Messaging.Worker.Domain.Entities.Conversacion", "Conversacion")
                        .WithMany("Participantes")
                        .HasForeignKey("ConversacionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Conversacion");
                });

            modelBuilder.Entity("Consumer.Messaging.Worker.Domain.Entities.Conversacion", b =>
                {
                    b.Navigation("Mensajes");

                    b.Navigation("Participantes");
                });

            modelBuilder.Entity("Consumer.Messaging.Worker.Domain.Entities.TipoMensaje", b =>
                {
                    b.Navigation("Mensajes");
                });
#pragma warning restore 612, 618
        }
    }
}
