
CREATE TABLE "usuarios" (
  "id" uuid PRIMARY KEY,
  "nombre_usuario" varchar UNIQUE NOT NULL,
  "email" varchar UNIQUE NOT NULL,
  "password_hash" varchar NOT NULL,
  "nombres" varchar NOT NULL,
  "apellidos" varchar NOT NULL,
  "fecha_nacimiento" date,
  "numero_telefono" varchar,
  "avatar_url" varchar,
  "creado_at" timestamp DEFAULT (now())
);

CREATE TABLE "refresh_tokens" (
  "id" uuid PRIMARY KEY,
  "usuario_id" uuid NOT NULL,
  "token" varchar NOT NULL UNIQUE,
  "fecha_expiracion" timestamp NOT NULL,
  "esta_revocado" boolean DEFAULT false NOT NULL,
  "creado_at" timestamp DEFAULT (now()),
  
  CONSTRAINT "fk_usuario_tokens" FOREIGN KEY ("usuario_id") 
    REFERENCES "usuarios" ("id") ON DELETE CASCADE
);

CREATE TABLE "participantes_conversacion" (
  "conversacion_id" uuid,
  "usuario_id" uuid,
  "unido_at" timestamp DEFAULT (now()),
  "ultimo_leido_at" timestamp,
  PRIMARY KEY ("conversacion_id", "usuario_id")
);

CREATE TABLE "tipos_mensaje" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "codigo" varchar UNIQUE NOT NULL,
  "descripcion" varchar
);

CREATE TABLE "mensajes" (
  "id" uuid PRIMARY KEY,
  "conversacion_id" uuid,
  "emisor_id" uuid,
  "tipo_mensaje_id" int,
  "contenido" text,
  "creado_at" timestamp DEFAULT (now())
);

COMMENT ON COLUMN "usuarios"."id" IS 'Identificador único del usuario';

COMMENT ON COLUMN "usuarios"."avatar_url" IS 'URL de la imagen en S3';

COMMENT ON COLUMN "conversaciones"."tipo" IS 'DIRECTO o GRUPAL';

COMMENT ON COLUMN "conversaciones"."nombre" IS 'Nulo si es un chat directo';

COMMENT ON COLUMN "participantes_conversacion"."ultimo_leido_at" IS 'Para calcular mensajes no leídos';

COMMENT ON COLUMN "tipos_mensaje"."codigo" IS 'Ej: TEXTO, IMAGEN, VIDEO, AUDIO';

COMMENT ON COLUMN "tipos_mensaje"."descripcion" IS 'Descripción legible del formato';

COMMENT ON COLUMN "mensajes"."tipo_mensaje_id" IS 'Referencia al catálogo de tipos';

COMMENT ON COLUMN "mensajes"."contenido" IS 'Texto del mensaje o URL de S3';

ALTER TABLE "participantes_conversacion" ADD FOREIGN KEY ("conversacion_id") REFERENCES "conversaciones" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "participantes_conversacion" ADD FOREIGN KEY ("usuario_id") REFERENCES "usuarios" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "mensajes" ADD FOREIGN KEY ("conversacion_id") REFERENCES "conversaciones" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "mensajes" ADD FOREIGN KEY ("emisor_id") REFERENCES "usuarios" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "mensajes" ADD FOREIGN KEY ("tipo_mensaje_id") REFERENCES "tipos_mensaje" ("id") DEFERRABLE INITIALLY IMMEDIATE;
